import type { Metadata } from "next";
import {Source_Sans_3 } from "next/font/google";
import "./globals.css";
import HomeBackground from "@/components/Home/HomeBackground";

const appFont = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${appFont.className}`}>
        {" "}
        <HomeBackground />
       <div className="min-h-screen ">{children}</div> 
      </body>
    </html>
  );
}
